### ISSUE TITLE
Implement end-user page feedback

### ISSUE THREAD

**Issue by sharifsalah** [AcademySoftwareFoundation/opencue.io#66]
Docsy includes support for a simple binary feedback system to ask visitors of opencue.io if the contents of a page is useful or not using buttons. This is especially useful for end-users who are might not be familiar with GitHub issues and provides a quick signal to gauge areas for improvement.

We should implement the feedback system by making the necessary changes to `config.toml`:

```toml
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
```
